apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omoikane.fullname" . }}-webhook-worker
  labels:
    {{- include "omoikane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.webhook }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "omoikane.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: webhook-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "omoikane.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: webhook-worker
    spec:
      containers:
        - name: webhook-worker
          image: {{ include "omoikane.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "dist/bin/webhook-worker.js"]
          env:
            {{- include "omoikane.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.webhook | nindent 12 }}
